# Site settings
title:       Pixyll
email:       nisarahm@usc.edu
author:      Nisar Ahmed
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         "http://pixyll.com"
animated: true